//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxJQueryCRUD.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Employee
    {
        public int EmployeeID { get; set; }
        [Required]
        public string Name { get; set; }
        public string Position { get; set; }
        public string Office { get; set; }
        public Nullable<int> Salary { get; set; }
        [Display(Name="Avartar")]
        public string ImagePath { get; set; }
        [NotMapped]
        public HttpPostedFileBase UpLoad { get; set; }

        public Employee()
        {
            ImagePath = @"~\Media\Images\avatar-default-icon.png";
            
        }
    }


}
